PixelUnShuffle
OpenPPL/ppl.pmx pull request #91
Opened 2024-07-15 07:25 UTC by Jzz24

2024-09-02 04:38 UTC, Alcanderian requested changes

2024-09-02 04:38 UTC, Alcanderian commented on model_zoo/intern_vit/huggingface/ConvertInternVLWeightToOPmx.py
这个文件已经冗余，可以删除

2024-09-02 04:38 UTC, Alcanderian commented on torch_function/TensorParallelRMSNorm.py
> +        embed_dim: int = 128, scale: float = 1.0,
embed dim不需要

计算逻辑
tp_variance = x_parallel.pow(2).mean(axis, keepdim=True)
if proc_group is not None and torch.distributed.get_world_size(proc_group) > 1:
       dist.all_reduce(tp_variance, op=dist.ReduceOp.SUM, async_op=False)
variance = tp_variance / (world_size * scale)

2024-09-02 04:38 UTC, Alcanderian commented on model_zoo/intern_vit/huggingface/ConvertInternVLPadWeightToOPmx.py
> +    args = parser.parse_args()
添加pad_to_head参数，默认1

padded_num_heads = (num_heads + pad_to_head - 1) // pad_to_head * pad_to_head

2024-09-02 04:38 UTC, Alcanderian commented on model_zoo/intern_vit/huggingface/ConvertInternVLPadWeightToOPmx.py
重命名

2024-09-02 04:38 UTC, Alcanderian commented on model_zoo/intern_vit/modeling/Params.py
> +    qk_norm: bool = True
根据pad添加 qk_norm_scale，padded_num_heads, padded_num_kv_heads，head_dim

2024-09-02 04:38 UTC, Alcanderian commented on model_zoo/intern_vit/huggingface/ConvertInternVLWeightToOPmx.py
> +
导出带有padded_num_heads和padded_num_kv_heads，还有qk_norm_scale, head_dim的json

2024-09-02 04:38 UTC, Alcanderian commented on model_zoo/intern_vit/modeling/static_batching/Model.py
> +        self.head_dim = 128 # tmp fix for pad num_head=25
读取 json的head_dim, 其他位置一样

2024-09-02 04:38 UTC, Alcanderian commented on model_zoo/intern_vit/modeling/static_batching/Model.py
> +        self.embed_dim = dim
不需要embed_dim

2024-09-02 04:54 UTC, Alcanderian commented on model_zoo/intern_vit/huggingface/ConvertInternVLPadWeightToOPmx.py
> +
导出带有padded_num_heads和padded_num_kv_heads，还有qk_norm_scale, head_dim的json

命名为opmx_params.json

同时要照顾原始的ConvertWeightToOPMX导出json
可以开一个新的intern_vl文件夹，里面带有vit的子文件夹
结构树
intern_vit
  ---- huggingface
          ---- convert_weight
intern_vl
  ---- huggingface
         ---- vit
               ---- convert_weight

2024-09-02 10:37 UTC, Alcanderian requested changes

2024-09-02 10:37 UTC, Alcanderian commented on model_zoo/intern_vit/huggingface/ConvertInternVLWeightToOPmx.py
> +    pmx_params_dict['qk_norm_scale'] = num_heads / pmx_params_dict['padded_num_heads']
除反了？

2024-09-02 11:51 UTC, Jzz24 commented on model_zoo/intern_vit/modeling/static_batching/Model.py
>              # TensorDumper.dump(output, "vision_proj_out")
else

2024-09-04 06:53 UTC, Alcanderian approved these changes

2024-09-04 06:54 UTC, merged